### ISSUE TITLE
don't work with `eslint<9`

### ISSUE THREAD

**Issue by CNSeniorious000** [antfu/eslint-config-flat-gitignore#11]
### Describe the bug

When I use `@antfu/eslint-config@2.21.3` with `eslint@8.57.0`, the ignored files in `.gitignore` still get checked.

I found that this repo has been updated recently so I believe it is caused by this and post isssue here. Perhaps I am wrong.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ruwbf2?file=package.json

If you delete the lock file and remove the `peerDependencies` field in `package.json`, then run eslint . again, it will fail.

### System Info

```Shell
System:
    OS: Linux 5.4 OpenCloudOS 8.8
    CPU: (2) x64 Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
    Memory: 1.60 GB / 3.58 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 18.16.0 - /usr/bin/node
    Yarn: 1.22.22 - ~/.local/share/pnpm/yarn
    npm: 10.8.1 - ~/.local/share/pnpm/npm
    pnpm: 9.4.0 - ~/.local/share/pnpm/pnpm
    bun: 1.1.17 - ~/.bun/bin/bun
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by CNSeniorious000** [comment]
@IgorKowalczyk Is this caused by #10 ? I am not familiar with eslint, I just read the version history timeline.

**Comment by xsjcTony** [comment]
It's expected, just ping the version of this library to `v0.1.5` until you upgrade your ESLint to 9
