### ISSUE TITLE
Replace `find-up` with `find-up-simple`

### ISSUE THREAD

**Issue by lachlancollins** [antfu/eslint-config-flat-gitignore#12]
### Clear and concise description of the problem

`eslint-config-flat-gitignore` currently has 8 dependencies, and 6 of them are sub-dependencies of  `find-up`: https://npmgraph.js.org/?q=find-up

### Suggested solution

Sindresorhus has an alternative package [`find-up-simple`](https://github.com/sindresorhus/find-up-simple), which has 0 dependencies.

It has [some limitations](https://github.com/sindresorhus/find-up-simple#how-is-it-different-from-find-up) compared to `find-up`, but none of these affect this package.

(It's probably also worth mentioning that I noticed both `find-up` and `find-up-simple` are ESM-only - `eslint-config-flat-gitignore` distributes both ESM and CJS but doesn't currently work in CJS because of this)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure, PR welcome :)
