### ISSUE TITLE
Ignore missing files

### ISSUE THREAD

**Issue by DaniFoldi** [antfu/eslint-config-flat-gitignore#2]
### Clear and concise description of the problem

Hi :wave:,

I'm not sure if this should be a bug report, or a feature request, so apologies if I miscategorized this issue.

Right now, when I use this plugin with either a custom option (`['.eslintignore', '.gitignore']`), or the default, and any of the files are missing, the `readFileSync` call throws, so eslint fails.

### Suggested solution

I believe, that to bring this plugin to parity with the old behavior where missing files are ignored, I would add a try/catch around the readFile, falling back to an empty string, in practice ignoring nothing (from that file).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I am ok adding an option to tolerate that (but prefer default to strict). PR welcome ;)
