### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [antfu/eslint-config-flat-gitignore#7]
### Clear and concise description of the problem

This won't work in a monorepo, let's say a pnpm/turborepo monorepo.
It only looks for a .gitignore in the cwd, but if use `eslint-config-flat-gitignore` in a workspace and i only use a .gitignore at the top-level of the monorepo, nothing will be found.

### Suggested solution

Maybe use something like [find-up](https://github.com/sindresorhus/find-up) to lookup for the `.gitignore` towards the top?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sure, PR welcome :)

**Comment by Superoryco** [comment]
This is great, but find-up is pure ESM start from [6.0.0](https://github.com/sindresorhus/find-up/releases/tag/v6.0.0), which breaks the cjs support of eslint-config-flat-gitignore, any suggestions?

**Comment by AndreaPontrandolfo** [comment]
@Superoryco 
yes, i understand that, but it's not actually too bad. 
If your project is not fully ESM yet, you can solve it just by setting eslint.config to ".mjs", so "eslint.config.mjs".
You can do so with eslint version `>= 8.57.0` or using [eslint-ts-patch](https://github.com/antfu/eslint-ts-patch).

**Comment by Superoryco** [comment]
@AndreaPontrandolfo Thank you for the tip, just [noticed](https://eslint.org/blog/2024/02/eslint-v8.57.0-released/) 😄
