### ISSUE TITLE
Support `core.excludesFile` property

### ISSUE THREAD

**Issue by vanyauhalin** [antfu/eslint-config-flat-gitignore#9]
### Clear and concise description of the problem

I have global git config in `~/.config/git/config` with:

```
[core]
excludesFile = ~/.config/git/self/ignore
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I don't think it's worth it for this plugin to search the config and parse the file (which would also require a parser) for every time ESLint runs - I'd suggest you to pass your own path explicitly in the argument.
